site_name: Documentation Raphaël Hirsch
site_description: Base de connaissances, notes techniques et ressources
site_url: https://documentation.raphael-hirsch.fr

theme:
  name: material
  language: fr
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair
  features:
    - navigation.tabs
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy

plugins:
  - search
  - tags:
      tags_file: tags.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Accueil: index.md
  - Système: 
      - Systeme/systeme.md
      - OS:
          - Systeme/OS/debian.md
      - Automatisation:
          - Systeme/Automatisation/ansible.md
      - Conteneurs: 
          - Systeme/Conteneurs/docker.md
          - Systeme/Conteneurs/kubernetes.md
      - Infrastructure_as_Code:
          - Systeme/Infrastructure_as_Code/terraform.md
      - Services:
          - Systeme/Services/dhcp.md
          - Systeme/Services/dns.md
  - Réseau: 
      - Reseau/reseau.md
      - Protocoles:
          - Reseau/Protocoles/ethernet_trames.md
          - Reseau/Protocoles/modele_osi.md
          - Reseau/Protocoles/tcp_ip.md
      - VPN:
          - Reseau/VPN/open_vpn.md
  - Cybersécurité: 
      - Cybersecurite/cybersecurite.md
      - Methodologies:
          - Cybersecurite/ebios.md
  - Management: 
      - Management/management.md
      - Gestion_de_projet:
          - Management/Gestion_de_projet/gantt.md
          - Management/Gestion_de_projet/matrice_des_risques.md
          - Management/Gestion_de_projet/pert.md
          - Management/Gestion_de_projet/qcd.md
          - Management/Gestion_de_projet/raci.md
      - Processus:
          - Management/Processus/diagramme_des_flux.md
          - Management/Processus/itil.md
      - Stratégie:
          - Management/Strategie/but_objectif.md
          - Management/Strategie/kpi.md
          - Management/Strategie/swot.md
  - Développement: Developpement/developpement.md
  - Autres:
      - Autres/autres.md
      - Projets:
          - Autres/rpg-tower-crawler.md
  - Index des Tags: tags.md
